apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: o63kgb5km-go 
  janus-idp.io/tekton: o63kgb5km-go
  backstage.io/kubernetes-id: o63kgb5km-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: o63kgb5km-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml