apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: o63kgb5km-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: o63kgb5km-go 
  name: o63kgb5km-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: o63kgb5km-go 
